package jp.linanfine.dsma.value._enum;

public enum MusicSortType {
    None,
    Recent,
    MusicName,
    Score,
    Rank,
    FullComboType,
    ComboCount,
    PlayCount,
    ClearCount,
    Difficulty,
    Pattern,
    SPDP,
    ID,
    RivalScore,
    RivalRank,
    RivalFullComboType,
    RivalComboCount,
    RivalPlayCount,
    RivalClearCount,
    RivalScoreDifference,
    RivalScoreDifferenceAbs,
    BpmMax,
    BpmMin,
    BpmAve,
    SeriesTitle,
}
